# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.19.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.19.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/yaroslav/Developer/Study/Computer Graphics/PW3-Triangles"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/yaroslav/Developer/Study/Computer Graphics/PW3-Triangles"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.19.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.19.2/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/yaroslav/Developer/Study/Computer Graphics/PW3-Triangles/CMakeFiles" "/Users/yaroslav/Developer/Study/Computer Graphics/PW3-Triangles//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/yaroslav/Developer/Study/Computer Graphics/PW3-Triangles/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named triangles

# Build rule for target.
triangles: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 triangles
.PHONY : triangles

# fast build rule for target.
triangles/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triangles.dir/build.make CMakeFiles/triangles.dir/build
.PHONY : triangles/fast

#=============================================================================
# Target rules for targets named lines

# Build rule for target.
lines: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lines
.PHONY : lines

# fast build rule for target.
lines/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lines.dir/build.make CMakeFiles/lines.dir/build
.PHONY : lines/fast

src/model.o: src/model.cpp.o

.PHONY : src/model.o

# target to build an object file
src/model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triangles.dir/build.make CMakeFiles/triangles.dir/src/model.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lines.dir/build.make CMakeFiles/lines.dir/src/model.cpp.o
.PHONY : src/model.cpp.o

src/model.i: src/model.cpp.i

.PHONY : src/model.i

# target to preprocess a source file
src/model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triangles.dir/build.make CMakeFiles/triangles.dir/src/model.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lines.dir/build.make CMakeFiles/lines.dir/src/model.cpp.i
.PHONY : src/model.cpp.i

src/model.s: src/model.cpp.s

.PHONY : src/model.s

# target to generate assembly for a file
src/model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triangles.dir/build.make CMakeFiles/triangles.dir/src/model.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lines.dir/build.make CMakeFiles/lines.dir/src/model.cpp.s
.PHONY : src/model.cpp.s

src/samples.o: src/samples.cpp.o

.PHONY : src/samples.o

# target to build an object file
src/samples.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triangles.dir/build.make CMakeFiles/triangles.dir/src/samples.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lines.dir/build.make CMakeFiles/lines.dir/src/samples.cpp.o
.PHONY : src/samples.cpp.o

src/samples.i: src/samples.cpp.i

.PHONY : src/samples.i

# target to preprocess a source file
src/samples.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triangles.dir/build.make CMakeFiles/triangles.dir/src/samples.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lines.dir/build.make CMakeFiles/lines.dir/src/samples.cpp.i
.PHONY : src/samples.cpp.i

src/samples.s: src/samples.cpp.s

.PHONY : src/samples.s

# target to generate assembly for a file
src/samples.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triangles.dir/build.make CMakeFiles/triangles.dir/src/samples.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lines.dir/build.make CMakeFiles/lines.dir/src/samples.cpp.s
.PHONY : src/samples.cpp.s

src/shapes.o: src/shapes.cpp.o

.PHONY : src/shapes.o

# target to build an object file
src/shapes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triangles.dir/build.make CMakeFiles/triangles.dir/src/shapes.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lines.dir/build.make CMakeFiles/lines.dir/src/shapes.cpp.o
.PHONY : src/shapes.cpp.o

src/shapes.i: src/shapes.cpp.i

.PHONY : src/shapes.i

# target to preprocess a source file
src/shapes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triangles.dir/build.make CMakeFiles/triangles.dir/src/shapes.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lines.dir/build.make CMakeFiles/lines.dir/src/shapes.cpp.i
.PHONY : src/shapes.cpp.i

src/shapes.s: src/shapes.cpp.s

.PHONY : src/shapes.s

# target to generate assembly for a file
src/shapes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triangles.dir/build.make CMakeFiles/triangles.dir/src/shapes.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lines.dir/build.make CMakeFiles/lines.dir/src/shapes.cpp.s
.PHONY : src/shapes.cpp.s

src/targets/lines.o: src/targets/lines.cpp.o

.PHONY : src/targets/lines.o

# target to build an object file
src/targets/lines.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lines.dir/build.make CMakeFiles/lines.dir/src/targets/lines.cpp.o
.PHONY : src/targets/lines.cpp.o

src/targets/lines.i: src/targets/lines.cpp.i

.PHONY : src/targets/lines.i

# target to preprocess a source file
src/targets/lines.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lines.dir/build.make CMakeFiles/lines.dir/src/targets/lines.cpp.i
.PHONY : src/targets/lines.cpp.i

src/targets/lines.s: src/targets/lines.cpp.s

.PHONY : src/targets/lines.s

# target to generate assembly for a file
src/targets/lines.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lines.dir/build.make CMakeFiles/lines.dir/src/targets/lines.cpp.s
.PHONY : src/targets/lines.cpp.s

src/targets/triangles.o: src/targets/triangles.cpp.o

.PHONY : src/targets/triangles.o

# target to build an object file
src/targets/triangles.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triangles.dir/build.make CMakeFiles/triangles.dir/src/targets/triangles.cpp.o
.PHONY : src/targets/triangles.cpp.o

src/targets/triangles.i: src/targets/triangles.cpp.i

.PHONY : src/targets/triangles.i

# target to preprocess a source file
src/targets/triangles.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triangles.dir/build.make CMakeFiles/triangles.dir/src/targets/triangles.cpp.i
.PHONY : src/targets/triangles.cpp.i

src/targets/triangles.s: src/targets/triangles.cpp.s

.PHONY : src/targets/triangles.s

# target to generate assembly for a file
src/targets/triangles.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triangles.dir/build.make CMakeFiles/triangles.dir/src/targets/triangles.cpp.s
.PHONY : src/targets/triangles.cpp.s

src/util.o: src/util.cpp.o

.PHONY : src/util.o

# target to build an object file
src/util.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triangles.dir/build.make CMakeFiles/triangles.dir/src/util.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lines.dir/build.make CMakeFiles/lines.dir/src/util.cpp.o
.PHONY : src/util.cpp.o

src/util.i: src/util.cpp.i

.PHONY : src/util.i

# target to preprocess a source file
src/util.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triangles.dir/build.make CMakeFiles/triangles.dir/src/util.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lines.dir/build.make CMakeFiles/lines.dir/src/util.cpp.i
.PHONY : src/util.cpp.i

src/util.s: src/util.cpp.s

.PHONY : src/util.s

# target to generate assembly for a file
src/util.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/triangles.dir/build.make CMakeFiles/triangles.dir/src/util.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lines.dir/build.make CMakeFiles/lines.dir/src/util.cpp.s
.PHONY : src/util.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... lines"
	@echo "... triangles"
	@echo "... src/model.o"
	@echo "... src/model.i"
	@echo "... src/model.s"
	@echo "... src/samples.o"
	@echo "... src/samples.i"
	@echo "... src/samples.s"
	@echo "... src/shapes.o"
	@echo "... src/shapes.i"
	@echo "... src/shapes.s"
	@echo "... src/targets/lines.o"
	@echo "... src/targets/lines.i"
	@echo "... src/targets/lines.s"
	@echo "... src/targets/triangles.o"
	@echo "... src/targets/triangles.i"
	@echo "... src/targets/triangles.s"
	@echo "... src/util.o"
	@echo "... src/util.i"
	@echo "... src/util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

